version: 0.2

env: 
  variables:
    IMAGE_NAME: my-api
    TASK_NAME: my-api-task
  
phases: 
  install:
    commands: 
      - echo "insalling tools"
      - aws --version
      - docker --version

  pre_build:
    commands: 
      - echo "loggin into AWS ECR"
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

      - echo "ACCOUNT ID is $ACCOUNT_ID"

      - |
        aws ecr get-login-password --region $AWS_DEFAULT_REGION \
        | docker login --username AWS --password-stdin \
        $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo "Building Docker image"
      - docker build -t $IMAGE_NAME .
      
      - IMAGE_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME
      - echo "$IMAGE_URI"

      - docker tag $IMAGE_NAME $IMAGE_URI:latest
      - docker tag $IMAGE_NAME $IMAGE_URI:$COMMIT_HASH


  post_build:
    commands: 
      - echo "Pushing Docker image to ECR---"
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME:latest

      - echo "Create task definition revision"
      - TASK_EXECUTION_ROLE=$(aws ecs describe-task-definition --task-definition $TASK_NAME --query 'taskDefinition.executionRoleArn' --output text)
      - cp task-def-template.json task-def.json
      - sed -i "s|<IMAGE_NAME>|$IMAGE_URI:latest|g" task-def.json
      - sed -i "s|<CONTAINER>|$IMAGE_NAME|g" task-def.json
      - sed -i "s|<TASK_ROLE>|$TASK_EXECUTION_ROLE|g" task-def.json
      - cat task-def.json
      - TASK_ARN=$(aws ecs register-task-definition --cli-input-json file://task-def.json | jq -r '.taskDefinition.taskDefinitionArn')

      - echo "Create appspec file for deployment"
      - cp appspec-template.json appspec.json
      - sed -i "s|<TASK>|$TASK_ARN|g" appspec.json 
      - sed -i "s|<CONTAINER>|$IMAGE_NAME|g" appspec.json
      - cat appspec.json
      
      - echo "build completed"

artifacts: 
  files:
    - appspec.json 
