AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  RepositoryName:
    Type: String
    Description: The name of the ECR repository.

Resources:
  ECRRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName

Outputs:
  ECRRepositoryUri:
    Description: URI of the ECR repository
    Value: !GetAtt ECRRepo.RepositoryUri
  ECRRepositoryName:
    Description: Name of the ECR repository
    Value: !Ref RepositoryName