---
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  ecrRepositoryName:
    Type: String
    Description: 'The name of the ECR repository'
  taskName:
    Type: String
    Description: 'The name of the ECS task definition'
  defaultRepositoryName:
    Type: String
    Description: 'The default ECR image name'
  vpcCidr:
    Type: String
    Description: 'The CIDR block for the VPC'
  subnet1Cidrs:
    Type: String
    Description: 'A comma-separated list of CIDR blocks for subnet 1'
  gitConnectionId: 
    Type: String
    Description: 'The Git connection ID'
  notificationEmail:
    Type: String
    Description: 'The email address to send notifications to'

Resources:  
  NetworkStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: ./network.yml
      Parameters:
        vpcCidr: !Ref vpcCidr
        subnet1Cidrs: !Ref subnet1Cidrs
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  LoadBalancerStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: ./load-balancer.yml
      Parameters:
        vpc: !GetAtt NetworkStack.Outputs.vpc
        subnets: !GetAtt NetworkStack.Outputs.subnets
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  ECSClusterStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: ./ecs-cluster.yml
      Parameters:
        vpc: !GetAtt NetworkStack.Outputs.vpc
        ecsSubnets: !GetAtt NetworkStack.Outputs.subnets
        loadBalancerSecurityGroup: !GetAtt LoadBalancerStack.Outputs.SecurityGoup
        prodTargetGroupArn: !GetAtt LoadBalancerStack.Outputs.ProdTargetGroupArn
        defaultRepositoryName: !Ref defaultRepositoryName
        ecrRepositoryName: !Ref ecrRepositoryName
        taskName: !Ref taskName
        notificationEmail: !Ref notificationEmail
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  CodeBuildStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: ./pipline/code-build.yml
      Parameters:
        artifactsBucketName: !Sub '${AWS::StackName}-artifacts-bucket-${AWS::Region}-${AWS::AccountId}'
        ecrRepositoryName: !Ref ecrRepositoryName
        ecsTaskName: !Ref taskName
        ecsTaskExecutionRoleName: !GetAtt ECSClusterStack.Outputs.ecsTaskExecutionRoleName
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  ArtifactsBucketStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: './artifacts-bucket.yml'
      Parameters:
        artifactsBucketName: !Sub '${AWS::StackName}-artifacts-bucket-${AWS::Region}-${AWS::AccountId}'
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  CodeDeployStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: ./pipline/code-deploy.yml
      Parameters:
        ECSClusterName: !GetAtt ECSClusterStack.Outputs.ECSClusterName
        ECSServiceName: !GetAtt ECSClusterStack.Outputs.ECSServiceName
        ProdTargetGroupName: !GetAtt LoadBalancerStack.Outputs.ProdTargetGroupName
        TestTargetGroupName: !GetAtt LoadBalancerStack.Outputs.TestTargetGroupName
        ProdListenerArn: !GetAtt LoadBalancerStack.Outputs.ProdListenerArn
        TestListenerArn: !GetAtt LoadBalancerStack.Outputs.TestListenerArn
        notificationEmail: !Ref notificationEmail
        logs500ErrorAlarm: !GetAtt ECSClusterStack.Outputs.logFilterMetric500Alarm

  CodePipelineStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: ./pipline/code-pipeline.yml
      Parameters:
        codeBuildProject: !GetAtt CodeBuildStack.Outputs.CodeBuildProjectName
        artifactsBucketName: !GetAtt ArtifactsBucketStack.Outputs.ArtifactsBucketName
        codeDeoloyApplicationName: !GetAtt CodeDeployStack.Outputs.CodeDeployApplicationName
        codeDeployDeploymentGroupName: !GetAtt CodeDeployStack.Outputs.CodeDeployDeploymentGroupName
        gitConnectionId: !Ref gitConnectionId
    DeletionPolicy:  Delete
    UpdateReplacePolicy: Delete
  
Outputs:
  LoadBalancerDNSName:
    Value: !GetAtt LoadBalancerStack.Outputs.LoadBalancerDNSName
    Description: 'The DNS name of the load balancer'