AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"


Parameters:
  codeBuildProject:
    Type: String
    Description: "The name of the CodeBuild project to use in the pipeline"
  artifactsBucketName:
    Type: String
    Description: "The name of the S3 bucket to store CodePipeline artifacts"
  gitConnectionId: 
    Type: String
    Description: "The CodeConnection Id to use"
  ECSClusterName:
    Type: String
    Description: "The name of the ECS cluster to deploy to"
  ECSServiceName:
    Type: String
    Description: "The name of the ECS service to deploy to"
  ecsTaskExecutionRoleName:
    Type: String
    Description: "The name of the ECS task execution role to assume"

Resources:

  ################### CodePipeline Role ###################
  CodePipelineServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "CodePipelineServiceRole"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "codepipeline.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "CodePipelinePolicy"
          PolicyDocument:
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:PutObject"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "codebuild:StartBuild"
                  - "codebuild:BatchGetBuilds"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "codeconnections:UseConnection"
                  - "codestar-connections:UseConnection"
                Resource: 
                  - !Sub "arn:aws:codestar-connections:*:${AWS::AccountId}:connection/${gitConnectionId}"
                  - !Sub "arn:aws:codeconnections:*:${AWS::AccountId}:connection/${gitConnectionId}"
              - Effect: "Allow"
                Action:
                  - "ecs:DescribeServices"
                  - "ecs:UpdateService"
                  - "ecs:DescribeTaskDefinition"
                  - "ecs:RegisterTaskDefinition"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "iam:PassRole"
                Resource:  !Sub "arn:aws:iam::${AWS::AccountId}:role/${ecsTaskExecutionRoleName}"

  ################### CodePipeline Pipeline ###################
  CodePipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStore:
        Type: "S3"
        Location: !Ref artifactsBucketName
      Stages:
        - Name: "Source"
          Actions:
            - Name: "SourceAction"
              ActionTypeId:
                Category: "Source"
                Owner: AWS
                Provider: "CodeStarSourceConnection"
                Version: "1"
              OutputArtifacts:
                - Name: "SourceOutput"
              Configuration:
                ConnectionArn: "arn:aws:codeconnections:us-east-1:547323802553:connection/9b6d746e-cb84-4a72-b897-78b5c19c0100"
                FullRepositoryId: "yassineBassi/my-api"
                BranchName: "ecs-blue-green"
        - Name: "Build"
          Actions:
            - Name: "BuildAction"
              ActionTypeId:
                Category: "Build"
                Owner: "AWS"
                Provider: "CodeBuild"
                Version: "1"
              InputArtifacts:
                - Name: "SourceOutput"
              OutputArtifacts:
                - Name: "BuildOutput"
              Configuration:
                ProjectName: !Ref codeBuildProject
        - Name: "Deploy"
          Actions:
            - Name: "DeployAction"
              ActionTypeId:
                Category: "Deploy"
                Owner: "AWS"
                Provider: "ECS"
                Version: "1"
              InputArtifacts:
                - Name: "BuildOutput"
              Configuration:
                ClusterName: !Ref ECSClusterName
                ServiceName: !Ref ECSServiceName
                FileName: "imagedefinitions.json"